kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mdo-core-ui
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: mdo-core-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mdo-core-ui
    spec:
      containers:
        - name: mdo-core-ui
          image: >-
            docker-push.prospecta.com/prospecta/mdo-analytics:development
          env:
            - name: spring.datasource.url
              value: >-
                jdbc:postgresql://postgresql.cdf1cbpxzgyx.ap-southeast-1.rds.amazonaws.com:5432/devops_test
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATASOURCE_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATASOURCE_PASSWD
            - name: spring.data.elasticsearch.client.reactive.endpoints
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS
            - name: spring.elasticsearch.rest.uris
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_ELASTICSEARCH_REST_URIS
            - name: mdo.config.jwt_rsk
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDO_CONFIG_JWT_RSK
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_USER
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PASSWD
            - name: spring.rabbitmq.addresses
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_ADDRESS
            - name: spring.rabbitmq.host
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_HOST
            - name: mdospark.path
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDOSPARK_PATH
            - name: mdospark.homepath
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDOSPARK_HOMEPATH
            - name: mdospark.version
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDOSPARK_VERSION
            - name: mdospark.endpoint
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDOSPARK_ENDPOINT
            - name: spring.rabbitmq.port
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PORT
            - name: spring.rabbitmq.ssl.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_SSL_ENABLED
            - name: server.canonical.url
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_CORE
            - name: server.name
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_NAME
            - name: grpc.server.port
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: GRPC_CORE_UI_SERVER_PORT
            - name: management.endpoint.health.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS
            - name: management.health.defaults.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_DEFAULTS_ENABLED
            - name: management.endpoint.health.group.alb.include
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_INCLUDE
            - name: management.endpoint.health.group.alb.show-components
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_SHOW-COMPONENTS
            - name: management.endpoint.health.group.alb.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_SHOW-DETAILS
            - name: management.health.group.alb.defaults.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_GROUP_ALB_DEFAULTS_ENABLED
            - name: dms.endpoint
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_DMS
            - name: grpc.crud.address.port
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: GRPC_CRUD_UI_SERVER_PORT
            - name: elastic.link
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_LINK
            - name: elastic.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_USERNAME
            - name: elastic.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_PASSWORD
            - name: grpc.crud.address.url
              value: 172.30.140.187
            - name: grpc.rule.address.url
              value: 172.30.91.36
            - name: grpc.rule.address.port
              value: '10003'
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_CORE
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: NEWRELIC_LICENSE_KEY
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.jpa.properties.hibernate.cache.use_second_level_cache
              value: 'true'
            - name: spring.jpa.properties.javax.persistence.sharedCache.mode
              value: ENABLE_SELECTIVE
            - name: spring.jpa.properties.hibernate.cache.use_query_cache
              value: 'true'
            - name: spring.jpa.properties.hibernate.cache.region.factory_class
              value: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            - name: spring.jpa.properties.hibernate.generate_statistics
              value: 'true'
            - name: spring.jpa.properties.hibernate.show_sql
              value: 'true'
            - name: spring.jpa.properties.hibernate.format_sql
              value: 'true'
            - name: spring.jpa.properties.hibernate.use_sql_comments
              value: 'true'
            - name: grpc.process.address.url
              value: 172.30.89.249
            - name: grpc.process.address.port
              value: '10009'
            - name: library.url
              value: dataplay.connekthub.com
            - name: library.token
              value: 6a380455-6b2f-4510-bb38-08a75c0275b4
            - name: HZ_CLUSTERNAME
              value: core-ui
            - name: spring.hazelcast.config
              value: 'classpath:hazelcast.xml'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: nexus-image-pull
      securityContext: {}
      schedulerName: default-scheduler
---
