---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: core-ui
  name: core-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: core-ui
    spec:
      containers:
      - image: docker.prospecta.com/prospecta/core-ui:development
        name: core-ui
        env:
        - name: server.port
          value: "8080"
        resources: {}
---
