---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: core-ui
  name: core-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: core-ui
    spec:
      containers:
      - image: docker.prospecta.com/prospecta/core-ui:development
        name: core-ui
        env:
        - name: server.port
          value: "8080"
        - name: spring.datasource.url
          value: jdbc:postgresql://192.168.10.43:5432/mdo_dev_core
        - name: spring.datasource.username
          value: 'null'
        - name: spring.datasource.password
          value: 'null'
        - name: spring.data.elasticsearch.client.reactive.endpoints
          value: https://192.168.10.47:9200
        - name: spring.elasticsearch.rest.uris
          value: https://192.168.10.47:9200
        - name: mdo.config.jwt_rsk
          value: 'null'
        - name: spring.rabbitmq.username
          value: 'null'
        - name: spring.rabbitmq.password
          value: 'null'
        - name: spring.rabbitmq.addresses
          value: 192.168.10.85:5672
        - name: spring.rabbitmq.host
          value: 192.168.10.85
        - name: mdospark.path
          value: 192.168.10.106:8080/opt/share/spark_main_fuse.properties
        - name: mdospark.homepath
          value: /opt/share
        - name: mdospark.version
          value: 2021.03.03-SNAPSHOT
        - name: mdospark.endpoint
          value: 192.168.10.106:8998/batches
        - name: spring.rabbitmq.port
          value: "5672"
        - name: spring.rabbitmq.ssl.enabled
          value: 'false'
        resources: {}
---
