---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: core-ui
  name: core-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: core-ui
    spec:
      containers:
      - image: docker.prospecta.com/prospecta/core-ui:development
        name: core-ui
        env:
        - name: server.port
          value: "8080"
        - name: spring.datasource.url
          value: jdbc:postgresql://192.168.10.43:5432/mdo_dev_core
        - name: spring.datasource.username
          value: 'null'
        - name: spring.datasource.password
          value: 'null'
        resources: {}
---
