---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fuse
  name: fuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fuse
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: fuse
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
