---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bgdsample
  name: fuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgdsample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgdsample
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgdsample
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
